# A push of two and its pop; eight pushes of two back to back and no pop; then a pattern push and two pops.
    .option norvc
    .text
    .globl main
main:
    li      t0, 2
    vsetvli t0, t0, e32, m1, ta, ma
    .rept 16
    nop
    .endr
    .balign 64
    sf.vc.iv    0x3, 0, v4, 4
    sf.vc.v.i   0x1, 0, v5, 4
    .rept 8
    sf.vc.iv    0x3, 0, v4, 4
    .endr
    .rept 128
    nop
    .endr
    .balign 64
    sf.vc.ivv   0x3, v2, v1, 8
    sf.vc.v.i   0x1, 0, v5, 4
    sf.vc.v.i   0x1, 0, v5, 4
    li      a0, 0
    ret
